// Copyright (c) 2021 Tailscale Inc & AUTHORS All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by gen_deps.go; DO NOT EDIT.

package integration

import (
	// And depend on a bunch of tailscaled innards, for Go's test caching.
	// Otherwise cmd/go never sees that we depend on these packages'
	// transitive deps when we run "go install tailscaled" in a child
	// process and can cache a prior success when a dependency changes.
	_ "golang.org/x/sys/windows"
	_ "golang.org/x/sys/windows/svc"
	_ "golang.org/x/sys/windows/svc/eventlog"
	_ "golang.org/x/sys/windows/svc/mgr"
	_ "golang.zx2c4.com/wireguard/windows/tunnel/winipcfg"
	_ "github.com/qwenode/tailscale/cmd/tailscaled/childproc"
	_ "github.com/qwenode/tailscale/control/controlclient"
	_ "github.com/qwenode/tailscale/derp/derphttp"
	_ "github.com/qwenode/tailscale/envknob"
	_ "github.com/qwenode/tailscale/ipn"
	_ "github.com/qwenode/tailscale/ipn/ipnserver"
	_ "github.com/qwenode/tailscale/ipn/store"
	_ "github.com/qwenode/tailscale/logpolicy"
	_ "github.com/qwenode/tailscale/logtail"
	_ "github.com/qwenode/tailscale/logtail/backoff"
	_ "github.com/qwenode/tailscale/net/dns"
	_ "github.com/qwenode/tailscale/net/interfaces"
	_ "github.com/qwenode/tailscale/net/netns"
	_ "github.com/qwenode/tailscale/net/portmapper"
	_ "github.com/qwenode/tailscale/net/proxymux"
	_ "github.com/qwenode/tailscale/net/socks5"
	_ "github.com/qwenode/tailscale/net/tsdial"
	_ "github.com/qwenode/tailscale/net/tshttpproxy"
	_ "github.com/qwenode/tailscale/net/tstun"
	_ "github.com/qwenode/tailscale/paths"
	_ "github.com/qwenode/tailscale/safesocket"
	_ "github.com/qwenode/tailscale/tailcfg"
	_ "github.com/qwenode/tailscale/tsweb"
	_ "github.com/qwenode/tailscale/types/flagtype"
	_ "github.com/qwenode/tailscale/types/key"
	_ "github.com/qwenode/tailscale/types/logger"
	_ "github.com/qwenode/tailscale/util/clientmetric"
	_ "github.com/qwenode/tailscale/util/multierr"
	_ "github.com/qwenode/tailscale/util/osshare"
	_ "github.com/qwenode/tailscale/util/winutil"
	_ "github.com/qwenode/tailscale/version"
	_ "github.com/qwenode/tailscale/version/distro"
	_ "github.com/qwenode/tailscale/wf"
	_ "github.com/qwenode/tailscale/wgengine"
	_ "github.com/qwenode/tailscale/wgengine/monitor"
	_ "github.com/qwenode/tailscale/wgengine/netstack"
	_ "github.com/qwenode/tailscale/wgengine/router"
)
